name: GH actions on pull_request
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [workflow_dispatch]
jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: .NET setup :(
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build project
        run: dotnet build --configuration ${{ matrix.configuration }}
        working-directory: src/
  load-artef:
    needs: dotnet-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        names: [ConsoleTestAddForMatrix, MatrixClassLibrary, XUnitTestsForMatrix]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: pwd
      run: pwd
    - name: ls path
      run: ls /src/${{ matrix.names }}/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
          name: Build ${{ matrix.configuration }} artifact
          path: ISRPO-Lab9-cpt/src/${{ matrix.names }}/bin/${{ matrix.configuration }}/net8.0/${{ matrix.names }}.dll
      
    
