name: GH actions on commit in main
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [workflow_dispatch]
# on:
  # push:
  #   branches: ["master"]
jobs:
  report_generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: .NET setup :(
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          
      - name: Install report-generator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        
      - name: Build project
        run: dotnet build --configuration Release
        working-directory: src/
        
      - name: Create cobertura
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
        working-directory: src/XUnitTestsForMatrix

      - name: Create report
        run: reportgenerator -reports:"coverage.cobertura.xml" -targetdir:"codecoveragereport" -reporttypes:Html
        working-directory: src/XUnitTestsForMatrix

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./src/XUnitTestsForMatrix/codecoveragereport/
